kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
  namespace: video-test
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
