kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test
  namespace: video-test
subjects:
  - kind: ServiceAccount
    name: test
    namespace: video-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test
